ingresses:
- "https://aap-soknad.dev.intern.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.dev.nav.no"
- name: DECORATOR_ENV
  value: "dev"
- name: LOGINSERVICE_URL
  value: "https://loginservice.dev.nav.no/login"