ingresses:
- "https://aap-soknad.dev.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.dev.nav.no"
- name: DECORATOR_ENV
  value: "dev"
- name: LOGINSERVICE_URL
  value: "https://loginservice.dev.nav.no/login"
- name: APP_URL
  value: "https://aap-soknad.dev.nav.no"
- name: SOKNAD_API_URL
  value: "http://soknad-api"
- name: SOKNAD_API_AUDIENCE
  value: "dev-gcp:aap:soknad-api"
externals:
  - "dekoratoren.dev.nav.no"
