name: "Cypress tests"
on:
  push:
    branches:
      - "main"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}-cypress"
jobs:
  "test":
    name: "test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "14"
          cache: "yarn"
      - name: "Cache client node_modules"
        id: "cache-node-modules"
        uses: "actions/cache@v2"
        with:
          path: 'node_modules'
          key: "${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}"
      - name: "Cache server node_modules"
        id: "cache-server-node-modules"
        uses: "actions/cache@v2"
        with:
          path: 'server/node_modules'
          key: "${{ runner.os }}-modules-${{ hashFiles('server/yarn.lock') }}"
      - name: "install dependencies Yarn"
        if: "steps.cache-node-modules.outputs.cache-hit != 'true'"
        run: "yarn install --frozen-lockfile"
      - name: "install server dependencies Yarn"
        if: "steps.cache-server-node-modules.outputs.cache-hit != 'true'"
        run: "yarn install --frozen-lockfile"
        working-directory: "server"
      - name: "Bygg klient(yarn run build)"
        run: "yarn run build"
      - name: "Bygg server(yarn run build)"
        run: "yarn run build"
        working-directory: "server"
      - name: "Run Cypress tests"
        uses: "cypress-io/github-action@v2"
        with:
          start: "yarn start"
          wait-on: "http://localhost:1234/"
          browser: "chrome"
        env:
          NODE_ENV: "localhost"
          USE_MOCK: "true"
      - name: "Upload screenshots if Cypress tests failed"
        uses: "actions/upload-artifact@v2"
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 5
